// ============================================================
// CONFIGURACOES DA LOJA
// Troque aqui: nome da loja, logo, WhatsApp, Instagram, cidade,
// texto de entrega, formas de pagamento e mensagens do WhatsApp.
// ============================================================
const STORE_CONFIG = {
  storeName: "Vitrine Prime",
  logoInitials: "VP",
  logoImage: "assets/brand/vitrine-prime-logo.png",
  whatsappNumber: "5569999999999",
  instagramUser: "primevitrine",
  instagramUrl: "https://www.instagram.com/primevitrine/",
  city: "Pimenta Bueno - RO",
  deliveryText: "Entrega em Pimenta Bueno e região",
  paymentMethods: "Pix, dinheiro e cartão",
  whatsappDefaultMessage: "Olá, vim pelo catálogo da {storeName} e gostaria de atendimento.",
  whatsappProductMessage: "Olá, tenho interesse no produto {codigo} - {nome}. Está disponível?",
};

const SITE_CONTENT = {
  metaDescription:
    "Vitrine Prime é uma loja catálogo de moda masculina, feminina e verão, com venda direta pelo WhatsApp.",
  nav: [
    "Início",
    "Mais Vendidos",
    "Feminino",
    "Masculino",
    "Infantil",
    "Oversized",
    "Moda Verão",
    "Acessórios",
    "Promoções",
    "Contato",
  ],
  buttons: {
    whatsapp: "Comprar pelo WhatsApp",
    buyWhatsapp: "Comprar pelo WhatsApp",
    viewCatalog: "Ver catálogo",
    viewInstagram: "Ver Instagram",
    sold: "Produto vendido",
    wantLook: "Quero esse look",
  },
  hero: {
    eyebrow: "VITRINE ONLINE",
    title: "Vitrine Prime",
    subtitle:
      "Moda masculina, feminina e verão em uma vitrine simples, moderna e direta pelo WhatsApp.",
    image: "fotos/banner-prime-vitrine.jpg",
    imageAlt: "Vitrine Prime moda online",
  },
  sections: {
    categoriesEyebrow: "Escolha por identidade",
    categoriesTitle: "Compre por estilo",
    categoriesDescription:
      "A vitrine é organizada por universos visuais para facilitar a escolha no celular.",
    categoryAction: "Ver produtos",
    newsEyebrow: "Mais vendidos",
    newsTitle: "Mais Vendidos",
    newsDescription: "Produtos em destaque para quem quer escolher rápido e comprar pelo WhatsApp.",
    catalogLink: "Ver catálogo completo",
    catalogEyebrow: "Catálogo",
    catalogTitle: "Catálogo Completo",
    catalogDescription: "Filtre por categoria, escolha sua peça e fale direto pelo WhatsApp.",
    promoEyebrow: "Preço especial",
    promoTitle: "Promoções",
    promoText: "Peças selecionadas com preço especial por tempo limitado.",
    promoAction: "Ver promoções",
    looksEyebrow: "Banners por estilo",
    looksTitle: "Identidades da Loja",
    contactEyebrow: "Atendimento",
    contactTitle: "Fale direto com a loja",
    contactText: "Tire dúvidas, peça fotos reais das peças e combine a melhor forma de entrega.",
    contactCardTitle: "Informações da loja",
  },
  footer: {
    text: "Vitrine Prime: moda masculina, feminina e verão com compra rápida pelo WhatsApp.",
    rights: "Todos os direitos reservados.",
  },
  lookMessage: "Olá, gostei do {look}. Pode me mandar mais informações?",
};

const CATEGORIES = [
  "Mais Vendidos",
  "Feminino",
  "Masculino",
  "Infantil",
  "Oversized",
  "Moda Verão",
  "Acessórios",
  "Promoções",
];

const CATALOG_FILTERS = [
  "Todos",
  "Mais Vendidos",
  "Feminino",
  "Masculino",
  "Infantil",
  "Oversized",
  "Moda Verão",
  "Acessórios",
  "Promoções",
];

const CATEGORY_CONTENT = {
  "Mais Vendidos": {
    subtitle: "Os produtos que mais chamam atenção da vitrine.",
    cta: "Ver destaques",
    icon: "MV",
  },
  Feminino: {
    subtitle: "Peças modernas e delicadas para todos os estilos.",
    cta: "Ver coleção",
    icon: "FE",
  },
  Masculino: {
    subtitle: "Moda urbana e forte para quem gosta de presença.",
    cta: "Explorar categoria",
    icon: "MA",
  },
  Infantil: {
    subtitle: "Roupas confortáveis e práticas para os pequenos.",
    cta: "Ver produtos",
    icon: "IN",
  },
  Oversized: {
    subtitle: "Peças largas e estilosas com visual atual.",
    cta: "Ver coleção",
    icon: "OS",
  },
  "Moda Verão": {
    subtitle: "Looks leves para dias de sol, praia e passeio.",
    cta: "Explorar verão",
    icon: "MV",
  },
  Acessórios: {
    subtitle: "Detalhes que completam o visual.",
    cta: "Ver detalhes",
    icon: "AC",
  },
  Promoções: {
    subtitle: "Ofertas especiais com preço mais atrativo.",
    cta: "Ver ofertas",
    icon: "%",
  },
};

// PRODUTOS DE EXEMPLO E FALLBACK
// Quando o Firebase estiver configurado, a vitrine busca produtos do Firestore.
// Se o Firebase ainda nao estiver configurado ou falhar, estes produtos mantem o site funcionando.
// Para cadastrar sem codigo, use o painel em /admin.
const PRODUCTS = [
  {
    id: 1,
    codigo: "CM001",
    nome: "Camiseta Oversized Preta",
    categoria: "Masculino",
    subcategoria: "Camisetas",
    tamanhos: [
      { label: "P", estoque: 2 },
      { label: "M", estoque: 3 },
      { label: "G", estoque: 4 },
      { label: "GG", estoque: 2 },
    ],
    cor: "Preta",
    tecido: "Algodão premium",
    preco: "69,90",
    precoAntigo: "",
    imagem: "fotos/camiseta-oversized-preta.jpg",
    status: "Disponível",
    destaque: true,
    promocao: false,
    descricao: "Camiseta oversized preta com visual urbano, forte e premium.",
  },
  {
    id: 2,
    codigo: "CA001",
    nome: "Camisa Social Azul",
    categoria: "Masculino",
    subcategoria: "Camisas",
    tamanhos: [
      { label: "M", estoque: 2 },
      { label: "G", estoque: 0 },
      { label: "GG", estoque: 1 },
    ],
    cor: "Azul",
    tecido: "Tricoline",
    preco: "119,90",
    precoAntigo: "",
    imagem: "fotos/camisa-social-slim-branca.jpg",
    status: "Disponível",
    destaque: true,
    promocao: false,
    descricao: "Camisa social azul para compor um visual moderno e alinhado.",
  },
  {
    id: 3,
    codigo: "BL001",
    nome: "Blusa Rosa Cropped",
    categoria: "Feminino",
    subcategoria: "Blusas",
    tamanhos: [
      { label: "P", estoque: 3 },
      { label: "M", estoque: 2 },
      { label: "G", estoque: 1 },
    ],
    cor: "Rosa",
    tecido: "Malha canelada",
    preco: "59,90",
    precoAntigo: "",
    imagem: "fotos/blusa-canelada-rosa.jpg",
    status: "Disponível",
    destaque: true,
    promocao: false,
    descricao: "Blusa cropped rosa com toque delicado e moderno.",
  },
  {
    id: 4,
    codigo: "VD001",
    nome: "Vestido Floral Rosa",
    categoria: "Feminino",
    subcategoria: "Vestidos",
    tamanhos: [
      { label: "P", estoque: 0 },
      { label: "M", estoque: 2 },
      { label: "G", estoque: 0 },
    ],
    cor: "Rosa",
    tecido: "Viscose",
    preco: "99,90",
    precoAntigo: "",
    imagem: "fotos/vestido-midi-floral.jpg",
    status: "Disponível",
    destaque: false,
    promocao: false,
    descricao: "Vestido floral leve, bonito e cheio de personalidade.",
  },
  {
    id: 5,
    codigo: "MV001",
    nome: "Camisa Praia Estampada",
    categoria: "Moda Verão",
    subcategoria: "Praia",
    tamanhos: [
      { label: "P", estoque: 2 },
      { label: "M", estoque: 0 },
      { label: "G", estoque: 2 },
      { label: "GG", estoque: 1 },
    ],
    cor: "Azul água",
    tecido: "Viscose leve",
    preco: "79,90",
    precoAntigo: "",
    imagem: "fotos/look-casual-urbano.jpg",
    status: "Disponível",
    destaque: true,
    promocao: false,
    descricao: "Camisa leve para praia, piscina, passeio e dias quentes.",
  },
  {
    id: 6,
    codigo: "MV002",
    nome: "Short Praia Areia",
    categoria: "Moda Verão",
    subcategoria: "Praia",
    tamanhos: [
      { label: "P", estoque: 0 },
      { label: "M", estoque: 2 },
      { label: "G", estoque: 1 },
    ],
    cor: "Bege areia",
    tecido: "Tactel leve",
    preco: "69,90",
    precoAntigo: "89,90",
    imagem: "fotos/bermuda-sarja-bege.jpg",
    status: "Disponível",
    destaque: false,
    promocao: true,
    descricao: "Short leve com clima de sol, férias e conforto.",
  },
  {
    id: 7,
    codigo: "MV003",
    nome: "Saída de Praia Coral",
    categoria: "Moda Verão",
    subcategoria: "Praia",
    tamanhos: [
      { label: "P", estoque: 0 },
      { label: "M", estoque: 0 },
      { label: "G", estoque: 0 },
    ],
    cor: "Coral",
    tecido: "Viscose leve",
    preco: "89,90",
    precoAntigo: "",
    imagem: "fotos/vestido-envelope-plus.jpg",
    status: "Esgotado",
    destaque: false,
    promocao: false,
    descricao: "Peça leve em coral para praia, piscina e passeios de verão.",
  },
  {
    id: 8,
    codigo: "AC001",
    nome: "Boné Preto Urban",
    categoria: "Acessórios",
    subcategoria: "Acessórios masculinos",
    tamanhos: [
      { label: "Único", estoque: 5 },
    ],
    cor: "Preto",
    tecido: "Algodão",
    preco: "49,90",
    precoAntigo: "",
    imagem: "fotos/bone-preto-urban.jpg",
    status: "Disponível",
    destaque: false,
    promocao: false,
    descricao: "Acessório minimalista para finalizar o visual urbano.",
  },
];

const LOOKS = [
  {
    nome: "Moda Masculina",
    descricao: "Peças urbanas para quem gosta de presença e estilo.",
    imagem: "fotos/look-casual-urbano.jpg",
    categoria: "Masculino",
  },
  {
    nome: "Moda Feminina",
    descricao: "Looks modernos, bonitos e cheios de personalidade.",
    imagem: "fotos/vestido-midi-floral.jpg",
    categoria: "Feminino",
  },
  {
    nome: "Moda Verão",
    descricao: "Roupas leves para praia, piscina, passeio e dias quentes.",
    imagem: "fotos/look-noite-evento.jpg",
    categoria: "Moda Verão",
  },
];

Object.assign(window, {
  STORE_CONFIG,
  SITE_CONTENT,
  CATEGORIES,
  CATALOG_FILTERS,
  CATEGORY_CONTENT,
  PRODUCTS,
  LOOKS,
});
